import NotistackProvider from "@/components/NotistackProvider";
import MuiLocalizationProvider from "@/components/mui/MuiLocalizationProvider";
import MuiThemeProvider from "@/theme/index";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";

// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            <MuiLocalizationProvider>
              <NotistackProvider>
                <body className={inter.className}>{children}</body>
              </NotistackProvider>
            </MuiLocalizationProvider>
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </StoreProvider>
    </html>
  );
}
